-- V5__Create_expenses_table.sql

CREATE TABLE expenses (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    amount DECIMAL(12,2) NOT NULL,
    expense_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    payment_method VARCHAR(20),
    merchant_name VARCHAR(200),
    location VARCHAR(500),
    tags VARCHAR(500),
    is_recurring BOOLEAN DEFAULT FALSE,
    currency_code VARCHAR(3) DEFAULT 'USD',
    exchange_rate DECIMAL(10,4),
    original_amount DECIMAL(12,2),
    original_currency VARCHAR(3),
    notes TEXT,
    reference_number VARCHAR(100),
    is_business_expense BOOLEAN DEFAULT FALSE,
    is_reimbursable BOOLEAN DEFAULT FALSE,
    reimbursed BOOLEAN DEFAULT FALSE,
    reimbursed_date DATE,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    team_id BIGINT,
    project_id BIGINT,
    approved_by BIGINT,
    approved_at TIMESTAMP,
    rejected_by BIGINT,
    rejected_at TIMESTAMP,
    rejection_reason VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_expense_user (user_id),
    INDEX idx_expense_category (category_id),
    INDEX idx_expense_date (expense_date),
    INDEX idx_expense_status (status),
    INDEX idx_expense_team (team_id),
    INDEX idx_expense_amount (amount),
    INDEX idx_expense_created (created_at),
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT
);